backend:
  name: git-gateway
  branch: master
media_folder: public/images/upload
public_folder: images/upload
collections:
  - name: "songs" # Used in routes, e.g., /admin/collections/blog
    label: "Songs" # Used in the UI
    folder: "/songs/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Artist", name: "artist", widget: "string" }
      - { label: "Copyright", name: "copyright", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
